FROM maven:3.9.5-eclipse-temurin-17

WORKDIR /app

# Copy the application first
COPY . .

# Start the application with dev profile
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'"]